file: '/home/www/bin/init_db.py' not exist!